version: '3.8'

services:
  toolbox-dev:
    image: ghcr.io/growlf/toolbox:latest
    environment:
      - TESTVAR=dev
    stdin_open: true
    tty: true
    command: ["/bin/zsh"]
    volumes:
      
      - ./:/app
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"  
    restart: unless-stopped

networks:
  default:
    name: toolbox-network
    driver: bridge
